### ISSUE TITLE
Updating rtodoist

### ISSUE THREAD

**Issue by emitanaka** [karthik/rtodoist#1]
@karthik would you mind if I update this package and submit a pull request?
It's implied [here](https://stackoverflow.com/questions/55445144/cannot-connect-to-todoist-rest-api-with-r) that this may be out of date and I've got the REST API working for this.

**Comment by karthik** [comment]
Please do. I'm happy to just transfer this repo over to you as I stopped using todoist many years ago.

**Comment by emitanaka** [comment]
Happy to take over :)
